[package]
name = "redis-client"
version = "0.1.0"
authors = ["gautier.tanguy"]
keywords = ["redis", "database"]
description = "Redis client for Rust."
homepage = "https://github.com/AsoSunag/redis-client"